CREATE TABLE IF NOT EXISTS episode_opportunity_context (
    episode_id TEXT PRIMARY KEY REFERENCES trading_episodes(episode_id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    active_side TEXT NOT NULL,
    shadow_side TEXT NOT NULL,
    actual_selected_side TEXT NOT NULL,
    blocked_side TEXT NOT NULL,
    direction TEXT NOT NULL,
    setup_generation INTEGER,
    active_group_id TEXT,
    active_base_position_identifier TEXT,
    shadow_build_valid INTEGER CHECK (shadow_build_valid IN (0, 1)),
    shadow_build_reason TEXT,
    long_reject TEXT,
    short_reject TEXT,
    source_provenance TEXT NOT NULL DEFAULT 'SOURCE_REPORTED'
);

CREATE TABLE IF NOT EXISTS episode_active_context (
    episode_id TEXT PRIMARY KEY REFERENCES trading_episodes(episode_id) ON DELETE CASCADE,
    active_entry_price REAL,
    active_current_price REAL,
    active_initial_risk REAL,
    active_initial_risk_distance REAL,
    active_current_r REAL,
    active_sl REAL,
    active_is_be INTEGER CHECK (active_is_be IN (0, 1)),
    active_tp1_done INTEGER CHECK (active_tp1_done IN (0, 1)),
    active_tp2_done INTEGER CHECK (active_tp2_done IN (0, 1)),
    active_runner_active INTEGER CHECK (active_runner_active IN (0, 1)),
    active_pyramid_adds INTEGER,
    active_bars_open INTEGER,
    active_locked_profit_r REAL,
    active_group_volume REAL,
    active_position_count INTEGER,
    active_value_at_event_r REAL,
    source_provenance TEXT NOT NULL DEFAULT 'SOURCE_REPORTED'
);

CREATE TABLE IF NOT EXISTS episode_opportunity_outcomes (
    episode_id TEXT PRIMARY KEY REFERENCES trading_episodes(episode_id) ON DELETE CASCADE,
    shadow_plus_1r_hit INTEGER CHECK (shadow_plus_1r_hit IN (0, 1)),
    shadow_minus_1r_hit INTEGER CHECK (shadow_minus_1r_hit IN (0, 1)),
    shadow_plus_1r_first INTEGER CHECK (shadow_plus_1r_first IN (0, 1)),
    shadow_minus_1r_first INTEGER CHECK (shadow_minus_1r_first IN (0, 1)),
    shadow_first_hit TEXT,
    shadow_mfe_r REAL,
    shadow_mae_r REAL,
    shadow_return_6bar_r REAL,
    shadow_return_12bar_r REAL,
    shadow_return_24bar_r REAL,
    shadow_return_48bar_r REAL,
    active_value_6bar_r REAL,
    active_value_12bar_r REAL,
    active_value_24bar_r REAL,
    active_value_48bar_r REAL,
    active_continuation_6bar_r REAL,
    active_continuation_12bar_r REAL,
    active_continuation_24bar_r REAL,
    active_continuation_48bar_r REAL,
    active_plus_1r_hit INTEGER CHECK (active_plus_1r_hit IN (0, 1)),
    active_minus_1r_hit INTEGER CHECK (active_minus_1r_hit IN (0, 1)),
    active_first_hit TEXT,
    actual_selected_build_valid INTEGER CHECK (actual_selected_build_valid IN (0, 1)),
    actual_selected_entry_price REAL,
    actual_selected_initial_sl REAL,
    actual_selected_risk_distance REAL,
    actual_selected_plus_1r_hit INTEGER CHECK (actual_selected_plus_1r_hit IN (0, 1)),
    actual_selected_minus_1r_hit INTEGER CHECK (actual_selected_minus_1r_hit IN (0, 1)),
    actual_selected_plus_1r_first INTEGER CHECK (actual_selected_plus_1r_first IN (0, 1)),
    actual_selected_minus_1r_first INTEGER CHECK (actual_selected_minus_1r_first IN (0, 1)),
    actual_selected_first_hit TEXT,
    actual_selected_mfe_r REAL,
    actual_selected_mae_r REAL,
    actual_selected_return_6bar_r REAL,
    actual_selected_return_12bar_r REAL,
    actual_selected_return_24bar_r REAL,
    actual_selected_return_48bar_r REAL,
    opportunity_diff_6bar_r REAL,
    opportunity_diff_12bar_r REAL,
    opportunity_diff_24bar_r REAL,
    opportunity_diff_48bar_r REAL,
    resolved INTEGER NOT NULL CHECK (resolved IN (0, 1)),
    outcome_timestamp_utc TEXT,
    incomplete_reason TEXT,
    outcome_schema_version TEXT NOT NULL,
    source_provenance TEXT NOT NULL DEFAULT 'SOURCE_REPORTED'
);

CREATE INDEX IF NOT EXISTS idx_opportunity_event ON episode_opportunity_context(event_type);
CREATE INDEX IF NOT EXISTS idx_opportunity_direction ON episode_opportunity_context(direction);
CREATE INDEX IF NOT EXISTS idx_active_context_episode ON episode_active_context(episode_id);
CREATE INDEX IF NOT EXISTS idx_opportunity_outcome_episode ON episode_opportunity_outcomes(episode_id);
